---
title: "archetype"
author: "Christa Spieth"
date: "4/3/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(archetypes)
library(vcd)
set.seed(1986)
```


```{r}
matches = read.csv('/team/projects/lol/segments_4_22.csv', header = TRUE)
matches$timestamp = matches$timestamp / 60000 # convert ms to min
matches[3:16] = sapply(matches[3:16], function(x) (x-mean(x))/sd(x)) # subset of data
```

```{r}
# to determine the best number of archetype profiles
as <- stepArchetypes(data = matches[-c(1,2)], k = 2:10, verbose = FALSE) # nrep=3 is default
screeplot(as)
```

```{r}
a <- bestModel(as[[4]]) # put best number of archetype profiles here
# xyplot(a, matches, chull = chull(matches))
# xyplot(a, matches, adata.show = TRUE)
# movieplot(a, matches) # this is to show how the archetype profiles were fitted
```

```{r}
# numbers and visualizations of archetype profiles
t(parameters(a))
barplot(a, matches, percentiles = TRUE)

# not sure how to get these working yet
# pcplot(a, skel2, data.col = as.numeric(matches$timestamp))
# ternaryplot(coef(a,'alphas'), col = as.numeric(matches$timestamp)) # uses library(vcd)
```

